name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: DushyayntRaghav/hello-world-docker-action-dush@v1.0.0
        with:
          who-to-greet: '@octocat'
